use serde::{Deserialize, Serialize};

/// Health check marker reserved for future worker ping support.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct HealthCheck;

/// Content of a chat message — plain text string or structured parts with images.
///
/// Text-only messages are serialized as `"string"` for backward compatibility.
/// VLM messages are serialized as `[{ "type": "text", "text": "..." }, ...]`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MessageContent {
    /// Plain text content (standard OpenAI format).
    Text(String),
    /// Structured content parts (text + images for VLM).
    Parts(Vec<ContentPart>),
}

impl MessageContent {
    /// Returns true if the content is non-empty.
    pub fn has_content(&self) -> bool {
        match self {
            MessageContent::Text(s) => !s.trim().is_empty(),
            MessageContent::Parts(parts) => {
                !parts.is_empty()
                    && parts.iter().any(|p| match p {
                        ContentPart::Text { text } => !text.trim().is_empty(),
                        ContentPart::ImageUrl { .. } => true,
                    })
            }
        }
    }
}

impl From<String> for MessageContent {
    fn from(s: String) -> Self {
        MessageContent::Text(s)
    }
}

impl From<&str> for MessageContent {
    fn from(s: &str) -> Self {
        MessageContent::Text(s.to_string())
    }
}

/// A single content part in a structured VLM message.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ContentPart {
    /// A text content block.
    Text {
        /// The text payload.
        text: String,
    },
    /// An image URL or data URI content block.
    ImageUrl {
        /// Image location metadata.
        image_url: ImageUrl,
    },
}

/// Image source for a VLM content part.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ImageUrl {
    /// URL, local path, or base64 data URI for the image.
    pub url: String,
    /// Optional detail hint ("auto", "low", "high").
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
}

/// A chat message in OpenAI-compatible format.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ChatMessage {
    /// The message role.
    pub role: MessageRole,
    /// The message content (text or structured parts with images).
    pub content: MessageContent,
}

/// The supported chat roles for Phase 1.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MessageRole {
    /// System message.
    System,
    /// User message.
    User,
    /// Assistant message.
    Assistant,
}

/// A single non-streaming chat completion request sent to the worker.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionRequest {
    /// Request identifier generated by the gateway.
    pub request_id: String,
    /// Model id requested by the client.
    pub model: String,
    /// Chat history.
    pub messages: Vec<ChatMessage>,
    /// Maximum number of generated tokens.
    pub max_tokens: u32,
    /// Sampling temperature.
    pub temperature: f32,
    /// Top-p sampling cutoff.
    pub top_p: f32,
    /// Maximum prompt tokens allowed for this request.
    pub max_prompt_tokens: u32,
    /// Maximum completion tokens allowed for this request.
    pub max_completion_tokens: u32,
    /// Maximum total tokens allowed for this request.
    pub max_total_tokens_per_request: u32,
    /// Whether the request should stream token deltas.
    #[serde(default)]
    pub stream: bool,
}
