use serde::{Deserialize, Serialize};

/// Health check marker reserved for future worker ping support.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct HealthCheck;

/// A chat message in OpenAI-compatible format.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ChatMessage {
    /// The message role.
    pub role: MessageRole,
    /// The text content.
    pub content: String,
}

/// The supported chat roles for Phase 1.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MessageRole {
    /// System message.
    System,
    /// User message.
    User,
    /// Assistant message.
    Assistant,
}

/// A single non-streaming chat completion request sent to the worker.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionRequest {
    /// Request identifier generated by the gateway.
    pub request_id: String,
    /// Model id requested by the client.
    pub model: String,
    /// Chat history.
    pub messages: Vec<ChatMessage>,
    /// Maximum number of generated tokens.
    pub max_tokens: u32,
    /// Sampling temperature.
    pub temperature: f32,
    /// Top-p sampling cutoff.
    pub top_p: f32,
}
