use serde::{Deserialize, Serialize};

/// Bootstrap success acknowledgment from the worker.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct WorkerReady;

/// Bootstrap failure details from the worker.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct WorkerError {
    /// Human-readable failure reason.
    pub message: String,
}

/// A single non-streaming completion result returned from the worker.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct ChatCompletionResponse {
    /// Request identifier generated by the gateway.
    pub request_id: String,
    /// Model id used by the worker.
    pub model: String,
    /// Final assistant text.
    pub text: String,
    /// Stop reason reported by the generator.
    pub finish_reason: String,
    /// Prompt token count.
    pub prompt_tokens: u32,
    /// Completion token count.
    pub completion_tokens: u32,
    /// Whether prompt cache reused prompt tokens.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_cache_hit: Option<bool>,
    /// Cached prompt token count reused for this request.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cached_tokens: Option<u32>,
    /// Prompt cache bytes referenced by this request.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_cache_bytes: Option<u64>,
    /// Active batch cache bytes observed for this request.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub active_batch_cache_bytes: Option<u64>,
    /// Prompt batch size when request was admitted.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_batch_size: Option<u32>,
    /// Decode batch size when request was completed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub decode_batch_size: Option<u32>,
}

/// A streamed completion delta emitted by the worker.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ChatCompletionDelta {
    /// Request identifier generated by the gateway.
    pub request_id: String,
    /// The streamed text delta.
    pub delta: String,
}
