use serde::{Deserialize, Serialize};

/// Bootstrap success acknowledgment from the worker.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct WorkerReady;

/// Bootstrap failure details from the worker.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct WorkerError {
    /// Human-readable failure reason.
    pub message: String,
}

/// A single non-streaming completion result returned from the worker.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ChatCompletionResponse {
    /// Request identifier generated by the gateway.
    pub request_id: String,
    /// Model id used by the worker.
    pub model: String,
    /// Final assistant text.
    pub text: String,
    /// Stop reason reported by the generator.
    pub finish_reason: String,
    /// Prompt token count.
    pub prompt_tokens: u32,
    /// Completion token count.
    pub completion_tokens: u32,
}
