use crate::status::ModelError;
use serde::{Deserialize, Serialize};

/// Bootstrap success acknowledgment from the worker.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct WorkerReady;

/// Bootstrap failure details from the worker.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct WorkerError {
    /// Human-readable failure reason.
    pub message: String,
    /// Structured startup failure details, when available.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<ModelError>,
}

/// A single non-streaming completion result returned from the worker.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct ChatCompletionResponse {
    /// Request identifier generated by the gateway.
    pub request_id: String,
    /// Model id used by the worker.
    pub model: String,
    /// Final assistant text.
    pub text: String,
    /// Stop reason reported by the generator.
    pub finish_reason: String,
    /// Prompt token count.
    pub prompt_tokens: u32,
    /// Completion token count.
    pub completion_tokens: u32,
    /// Whether prompt cache reused prompt tokens.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_cache_hit: Option<bool>,
    /// Cached prompt token count reused for this request.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cached_tokens: Option<u32>,
    /// Prompt cache bytes referenced by this request.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_cache_bytes: Option<u64>,
    /// Active batch cache bytes observed for this request.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub active_batch_cache_bytes: Option<u64>,
    /// Prompt batch size when request was admitted.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_batch_size: Option<u32>,
    /// Decode batch size when request was completed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub decode_batch_size: Option<u32>,
    /// Configured prompt batch size for the backend.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub configured_prompt_batch_size: Option<u32>,
    /// Configured decode batch size for the backend.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub configured_decode_batch_size: Option<u32>,
    /// Backend family that produced this response.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub backend: Option<String>,
    /// Logical modality for the response (text or vlm).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub modality: Option<String>,
    /// APC mode reported by the worker.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub apc_mode: Option<String>,
    /// Final scheduler stage recorded for the request.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scheduler_stage: Option<String>,
    /// Stage where cancellation occurred, when applicable.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cancellation_stage: Option<String>,
    /// Time spent waiting before decode started.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub queue_time_ms: Option<u32>,
    /// Time spent in prompt processing before decode.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prefill_time_ms: Option<u32>,
    /// Time to first printable token.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ttft_ms: Option<u32>,
    /// Time spent in decode.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub decode_time_ms: Option<u32>,
    /// End-to-end completion time.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub completion_time_ms: Option<u32>,
    /// Latency for the worker scheduler tick that produced this response.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scheduler_tick_latency_ms: Option<u32>,
    /// Delay between the arbitration round start and this backend tick.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arbitration_delay_ms: Option<u32>,
    /// Worker-side cancellation count at the time of emission.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub worker_cancellation_count: Option<u32>,
    /// Worker-side error count at the time of emission.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub worker_error_count: Option<u32>,
    /// Whether the VLM vision-feature cache hit.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vision_feature_cache_hit: Option<bool>,
    /// Vision-feature cache bytes referenced by this request.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vision_feature_cache_bytes: Option<u64>,
    /// Vision-feature cache entry count.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vision_feature_cache_entries: Option<u32>,
    /// Vision-feature cache evictions count.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vision_feature_cache_evictions: Option<u32>,
    /// Vision-encoder latency in milliseconds.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vision_encoder_latency_ms: Option<u32>,
    /// Embedding preparation latency in milliseconds.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub embedding_latency_ms: Option<u32>,
    /// Prompt-cache entry count for the backend.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_cache_entries: Option<u32>,
    /// Prompt-cache eviction count for the backend.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_cache_evictions: Option<u32>,
    /// Peak memory observed by the generator.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub peak_memory_bytes: Option<u64>,
    /// Source image width for VLM requests.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image_width: Option<u32>,
    /// Source image height for VLM requests.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image_height: Option<u32>,
}

/// A streamed completion delta emitted by the worker.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ChatCompletionDelta {
    /// Request identifier generated by the gateway.
    pub request_id: String,
    /// The streamed text delta.
    pub delta: String,
}

/// Per-step scheduler metrics emitted independently from request terminals.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SchedulerMetricsEvent {
    /// Backend family that emitted metrics.
    pub backend: String,
    /// Logical modality for metrics ownership.
    pub modality: String,
    /// Scheduler phase that produced this step.
    pub phase: String,
    /// Tokens scheduled in this step.
    pub scheduled_tokens: u32,
    /// Batch size for this step.
    pub batch_size: u32,
    /// Current waiting-request count.
    pub waiting_requests: u32,
    /// Current running-request count.
    pub running_requests: u32,
    /// End-to-end tick latency in milliseconds.
    pub scheduler_tick_latency_ms: u32,
    /// Physical model-forward mode selected by the executor.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub forward_mode: Option<String>,
    /// Number of requests submitted to the physical model invocation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub physical_batch_size: Option<u32>,
    /// Number of physical model invocations used by the scheduler step.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_forward_count: Option<u32>,
    /// Physical KV-cache backend label.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cache_backend: Option<String>,
    /// Attention implementation label.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub attention_backend: Option<String>,
    /// Attention forward mode observed by the backend.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub attention_mode: Option<String>,
    /// Attention dispatch latency in milliseconds.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub attention_time_ms: Option<u32>,
    /// Executor request validation and tensor layout time.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub executor_prepare_ms: Option<u32>,
    /// Executor KV reservation time.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub executor_reserve_ms: Option<u32>,
    /// Executor model forward graph construction time.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub executor_forward_ms: Option<u32>,
    /// Executor sampling graph construction time.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub executor_sample_ms: Option<u32>,
    /// Executor MLX evaluation latency.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub executor_eval_ms: Option<u32>,
    /// Executor KV commit latency.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub executor_commit_ms: Option<u32>,
    /// Model embedding graph latency when graph profiling is enabled.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_graph_embedding_ms: Option<u32>,
    /// Model projection graph latency when graph profiling is enabled.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_graph_projection_total_ms: Option<u32>,
    /// Model attention graph latency when graph profiling is enabled.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_graph_attention_ms: Option<u32>,
    /// Model MLP graph latency when graph profiling is enabled.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_graph_mlp_total_ms: Option<u32>,
    /// Model normalization graph latency when graph profiling is enabled.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_graph_norm_ms: Option<u32>,
    /// Model LM-head graph latency when graph profiling is enabled.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_graph_lm_head_ms: Option<u32>,
    /// Sum of per-layer profiled graph latency.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_graph_layer_total_ms: Option<u32>,
    /// Slowest profiled transformer layer latency.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_graph_worst_layer_ms: Option<u32>,
    /// Index of the slowest profiled transformer layer.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_graph_worst_layer_index: Option<u32>,
    /// Total physical KV pages.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_pages: Option<u32>,
    /// Physical KV pages referenced by active requests.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub used_pages: Option<u32>,
    /// Physical KV pages available for allocation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub free_pages: Option<u32>,
    /// Physical KV pages protected by in-flight reservations.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pinned_pages: Option<u32>,
    /// Unused logical token slots in active requests' final pages.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub internal_fragmentation_tokens: Option<u32>,
    /// Bytes occupied by referenced physical KV pages.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub active_kv_bytes: Option<u64>,
    /// Number of pre-mutation KV allocation failures.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub allocation_failures: Option<u64>,
    /// Configured number of tokens per KV page.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub page_size: Option<u32>,
    /// Selected prefix-index strategy.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prefix_strategy: Option<String>,
    /// Prefix-cache lookup count.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prefix_queries: Option<u64>,
    /// Prefix-cache hit count.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prefix_hits: Option<u64>,
    /// Prefix-cache miss count.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prefix_misses: Option<u64>,
    /// Tokens reused from prefix-cache pages.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prefix_reused_tokens: Option<u64>,
    /// Pages reused from prefix-cache pages.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prefix_reused_pages: Option<u64>,
    /// Prefix-cache entry count.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prefix_entries: Option<u64>,
    /// Prefix-cache stored bytes.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prefix_bytes: Option<u64>,
    /// Prefix-cache pages currently pinned by attached requests.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prefix_pinned_pages: Option<u64>,
    /// Block-hash matches rejected by exact verification.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prefix_collisions_rejected: Option<u64>,
    /// Prefix-cache eviction count.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prefix_evictions: Option<u64>,
    /// Number of radix-tree nodes.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub radix_nodes: Option<u64>,
    /// Number of radix node splits.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub radix_splits: Option<u64>,
    /// Pages stored on radix nodes that have children.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub radix_shared_pages: Option<u64>,
    /// Pages protected by active radix matches.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub radix_protected_pages: Option<u64>,
    /// Pages on evictable radix leaves.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub radix_evictable_pages: Option<u64>,
    /// Longest token depth in the radix tree.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub radix_tree_depth: Option<u64>,
    /// Number of radix leaf evictions.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub radix_leaf_evictions: Option<u64>,
}
